name:                ardu-gen
version:             0.1.0.0
github:              "t4ccer/ardu-gen"
license:             BSD3
author:              "t4ccer"
maintainer:          "t4ccer@gmail.com"
copyright:           "2020 t4ccer"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/t4ccer/ardu-gen#readme>

dependencies:
- base >= 4.14 && < 5

library:
  source-dirs: src
